### PR TITLE
Update the JSON instruction schema

### PR DESCRIPTION
**Pull request by RohitPrasadBhatt**
This is required for compatibility with sanity checking of JSON file.

### CODE REVIEW

**Comment by LaurinFischer** [comment]
Hi Rohid, 
it's not really clear to me why this change is needed from your side. If all tests run smoothly this should be fine though, have you tried this?

**Comment by RohitPrasadBhatt** [comment]
See this : https://stackoverflow.com/a/15721401.
Earlier I used ``json.loads()`` to serialize the json dictionary and it automatically converted round brackets to square. I think we should do it properly right at the source.

**Review by eggerdj — APPROVED** [review]
LGTM

**Comment by eggerdj** [comment]
@LaurinFischer This is more for correctness than anything else. JSon will serialize the Tuple as a List so we might as we use a list from the start.

**Pull request merged**
