### PR TITLE
Gate library and example for synqs singlequdit backend

### PR DESCRIPTION
**Pull request by RohitPrasadBhatt**
This allows for using our singlequdit backend.

### CODE REVIEW

**Comment by LaurinFischer** [comment]
Hi Rohid, 
this looks pretty cool, nice to see the experimental data reproduced. 
 A few comments:
 - I'm not sure whether this repo is the right place for the spin demo notebook, as it requires access to your own simulator backend. Right now you are disclosing username and password to this, is this intended?
 - If we want to put this as a tutorial here, maybe it would make senses to instead call the spin simulator backend already included in the repo. 
 - The`RLXGate`, `RLZGate`, `RLZ2Gate` gates look pretty much like duplicates of some of the gates already defined in the `spin_gate_library`, no? I think you should be able to use these rather than having to create your own gate library. 
 - The load instruction is indeed something which needs to be added. I would suggest just adding this to the existing spin gate library.

**Comment by fretchen** [comment]
@LaurinFischer concerning your suggestion with spin demo notebook. This means that it would be more 'proper' to build a package for all _synqs_ devices/simulators that basically builds up on `qiskit-cold-atom` as an external dependency ? Same would hold for anyone else that would like to expose his back-ends ?

**Review by eggerdj — CHANGES_REQUESTED** [review]
The notebook looks good and I think that it has its place here. We should however make some changes to it:
* By default we should use the simulator in this package to make the NB self-contained. I.e. users only need to install the code in this package and it will run. That being said you can add in the NB some code pointing to the remote simulator that you have built. There are several ways one could have both with local by default: a) comment out code b) use a boolean flag c) have a field where the user can add his credentials (left blank by default) and then inspect the backends of the provider and chose synqsys if available and otherwise default to local. My preference is for option c).
* We could try and make the notebook a little more explanatory, e.g. what is squeezing.
* Some quantities are not explained, e.g. what is the variable `t1`? You could structure the code as follows:
```
# comment describing variable1
variable1 = ...

# comment describing variable 2
variable2 = ...
```

**Comment by fretchen** [comment]
I think that this PR is not required anymore as it was already implemented in #17

**Pull request closed without merging**
